# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1246, 713)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/tilamisu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: white")
        self.usrname = QtWidgets.QLineEdit(Dialog)
        self.usrname.setGeometry(QtCore.QRect(410, 180, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usrname.setFont(font)
        self.usrname.setStyleSheet("QTextEdit{\n"
"    font-family: \'SimHei\', \n"
"    serif;font-size: 14px;\n"
"    background-color:#ffffff; color:#000000\n"
"}\n"
"")
        self.usrname.setText("")
        self.usrname.setObjectName("usrname")
        self.passwd = QtWidgets.QLineEdit(Dialog)
        self.passwd.setGeometry(QtCore.QRect(410, 240, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwd.setFont(font)
        self.passwd.setStyleSheet("QTextEdit{\n"
"    font-family: \'SimHei\', \n"
"    serif;font-size: 14px;\n"
"    background-color:#ffffff; color:#000000;\n"
"    background-color: rgba(0,0,0,150)\n"
"}")
        self.passwd.setText("")
        self.passwd.setObjectName("passwd")
        self.labelUsrname = QtWidgets.QLabel(Dialog)
        self.labelUsrname.setGeometry(QtCore.QRect(320, 190, 71, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.labelUsrname.setFont(font)
        self.labelUsrname.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: #1E90FF;\n"
"font-family: \'SimHei\', serif;\n"
"font-size: 20px;\n"
"}\n"
"QLabel:hover{background-color: #9370DB    ;color: #ffffff;font-family: \'SimHei\', serif;font-size: 18px;}")
        self.labelUsrname.setObjectName("labelUsrname")
        self.labelPasswd = QtWidgets.QLabel(Dialog)
        self.labelPasswd.setGeometry(QtCore.QRect(320, 250, 72, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.labelPasswd.setFont(font)
        self.labelPasswd.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: #1E90FF;\n"
"font-family: \'SimHei\', serif;\n"
"font-size: 20px;\n"
"}\n"
"QLabel:hover{background-color: #9370DB    ;color: #ffffff;font-family: \'SimHei\', serif;font-size: 18px;}")
        self.labelPasswd.setObjectName("labelPasswd")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(430, 540, 121, 41))
        self.startButton.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:8px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        self.startButton.setObjectName("startButton")
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(670, 540, 121, 41))
        self.exitButton.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:8px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        self.exitButton.setObjectName("exitButton")
        self.reasonText = QtWidgets.QTextEdit(Dialog)
        self.reasonText.setGeometry(QtCore.QRect(410, 360, 411, 121))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.reasonText.setFont(font)
        self.reasonText.setStyleSheet("QTextEdit{\n"
"    font-family: \'SimHei\', \n"
"    serif;font-size: 14px;\n"
"    background-color:#ffffff; color:#000000\n"
"}\n"
"")
        self.reasonText.setObjectName("reasonText")
        self.labelPasswd_2 = QtWidgets.QLabel(Dialog)
        self.labelPasswd_2.setGeometry(QtCore.QRect(300, 410, 91, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.labelPasswd_2.setFont(font)
        self.labelPasswd_2.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: #1E90FF;\n"
"font-family: \'SimHei\', serif;\n"
"font-size: 20px;\n"
"}\n"
"QLabel:hover{background-color: #9370DB    ;color: #ffffff;font-family: \'SimHei\', serif;font-size: 18px;}")
        self.labelPasswd_2.setObjectName("labelPasswd_2")
        self.IsSchool = QtWidgets.QRadioButton(Dialog)
        self.IsSchool.setGeometry(QtCore.QRect(940, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.IsSchool.setFont(font)
        self.IsSchool.setStyleSheet("background-color: transparent;")
        self.IsSchool.setCheckable(True)
        self.IsSchool.setChecked(True)
        self.IsSchool.setObjectName("IsSchool")
        self.labelImgae = QtWidgets.QLabel(Dialog)
        self.labelImgae.setGeometry(QtCore.QRect(500, 30, 171, 141))
        self.labelImgae.setStyleSheet("border-image: url(:/jpg/tom.jpg)")
        self.labelImgae.setText("")
        self.labelImgae.setObjectName("labelImgae")
        self.labelClass = QtWidgets.QLabel(Dialog)
        self.labelClass.setGeometry(QtCore.QRect(320, 310, 71, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.labelClass.setFont(font)
        self.labelClass.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: #1E90FF;\n"
"font-family: \'SimHei\', serif;\n"
"font-size: 20px;\n"
"}\n"
"QLabel:hover{background-color: #9370DB    ;color: #ffffff;font-family: \'SimHei\', serif;font-size: 18px;}")
        self.labelClass.setObjectName("labelClass")
        self.Class = QtWidgets.QLineEdit(Dialog)
        self.Class.setGeometry(QtCore.QRect(410, 300, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Class.setFont(font)
        self.Class.setStyleSheet("QTextEdit{\n"
"    font-family: \'SimHei\', \n"
"    serif;font-size: 14px;\n"
"    background-color:#ffffff; color:#000000\n"
"}\n"
"")
        self.Class.setText("")
        self.Class.setObjectName("Class")
        self.NotIsSchool = QtWidgets.QRadioButton(Dialog)
        self.NotIsSchool.setGeometry(QtCore.QRect(940, 180, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.NotIsSchool.setFont(font)
        self.NotIsSchool.setStyleSheet("background-color: transparent;")
        self.NotIsSchool.setCheckable(True)
        self.NotIsSchool.setChecked(False)
        self.NotIsSchool.setObjectName("NotIsSchool")
        self.labelUsrname_2 = QtWidgets.QLabel(Dialog)
        self.labelUsrname_2.setGeometry(QtCore.QRect(890, 250, 21, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.labelUsrname_2.setFont(font)
        self.labelUsrname_2.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: #1E90FF;\n"
"font-family: \'SimHei\', serif;\n"
"font-size: 20px;\n"
"}\n"
"QLabel:hover{background-color: #9370DB    ;color: #ffffff;font-family: \'SimHei\', serif;font-size: 18px;}")
        self.labelUsrname_2.setObjectName("labelUsrname_2")
        self.province = QtWidgets.QLineEdit(Dialog)
        self.province.setGeometry(QtCore.QRect(930, 240, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.province.setFont(font)
        self.province.setStyleSheet("QTextEdit{\n"
"    font-family: \'SimHei\', \n"
"    serif;font-size: 14px;\n"
"    background-color:#ffffff; color:#000000\n"
"}\n"
"")
        self.province.setText("")
        self.province.setObjectName("province")
        self.labelUsrname_3 = QtWidgets.QLabel(Dialog)
        self.labelUsrname_3.setGeometry(QtCore.QRect(890, 310, 31, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.labelUsrname_3.setFont(font)
        self.labelUsrname_3.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: #1E90FF;\n"
"font-family: \'SimHei\', serif;\n"
"font-size: 20px;\n"
"}\n"
"QLabel:hover{background-color: #9370DB    ;color: #ffffff;font-family: \'SimHei\', serif;font-size: 18px;}")
        self.labelUsrname_3.setObjectName("labelUsrname_3")
        self.city = QtWidgets.QLineEdit(Dialog)
        self.city.setGeometry(QtCore.QRect(930, 300, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.city.setFont(font)
        self.city.setStyleSheet("QTextEdit{\n"
"    font-family: \'SimHei\', \n"
"    serif;font-size: 14px;\n"
"    background-color:#ffffff; color:#000000\n"
"}\n"
"")
        self.city.setText("")
        self.city.setObjectName("city")
        self.labelUsrname_4 = QtWidgets.QLabel(Dialog)
        self.labelUsrname_4.setGeometry(QtCore.QRect(890, 370, 31, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.labelUsrname_4.setFont(font)
        self.labelUsrname_4.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: #1E90FF;\n"
"font-family: \'SimHei\', serif;\n"
"font-size: 20px;\n"
"}\n"
"QLabel:hover{background-color: #9370DB    ;color: #ffffff;font-family: \'SimHei\', serif;font-size: 18px;}")
        self.labelUsrname_4.setObjectName("labelUsrname_4")
        self.qu = QtWidgets.QLineEdit(Dialog)
        self.qu.setGeometry(QtCore.QRect(930, 360, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qu.setFont(font)
        self.qu.setStyleSheet("QTextEdit{\n"
"    font-family: \'SimHei\', \n"
"    serif;font-size: 14px;\n"
"    background-color:#ffffff; color:#000000\n"
"}\n"
"")
        self.qu.setText("")
        self.qu.setObjectName("qu")
        self.labelUsrname_5 = QtWidgets.QLabel(Dialog)
        self.labelUsrname_5.setGeometry(QtCore.QRect(880, 430, 51, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(-1)
        self.labelUsrname_5.setFont(font)
        self.labelUsrname_5.setStyleSheet("QLabel{\n"
"background-color: transparent;\n"
"color: #1E90FF;\n"
"font-family: \'SimHei\', serif;\n"
"font-size: 20px;\n"
"}\n"
"QLabel:hover{background-color: #9370DB    ;color: #ffffff;font-family: \'SimHei\', serif;font-size: 18px;}")
        self.labelUsrname_5.setObjectName("labelUsrname_5")
        self.living = QtWidgets.QLineEdit(Dialog)
        self.living.setGeometry(QtCore.QRect(930, 420, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.living.setFont(font)
        self.living.setStyleSheet("QTextEdit{\n"
"    font-family: \'SimHei\', \n"
"    serif;font-size: 14px;\n"
"    background-color:#ffffff; color:#000000\n"
"}\n"
"")
        self.living.setText("")
        self.living.setObjectName("living")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(870, 490, 341, 141))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "自动健康申报"))
        self.labelUsrname.setText(_translate("Dialog", "学号"))
        self.labelPasswd.setText(_translate("Dialog", "密码"))
        self.startButton.setText(_translate("Dialog", "申报"))
        self.exitButton.setText(_translate("Dialog", "退出"))
        self.reasonText.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimHei\',\'serif\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">无</span></p></body></html>"))
        self.labelPasswd_2.setText(_translate("Dialog", "出行记录"))
        self.IsSchool.setText(_translate("Dialog", "在校"))
        self.labelClass.setText(_translate("Dialog", "班级"))
        self.NotIsSchool.setText(_translate("Dialog", "不在校"))
        self.labelUsrname_2.setText(_translate("Dialog", "省"))
        self.labelUsrname_3.setText(_translate("Dialog", "市"))
        self.labelUsrname_4.setText(_translate("Dialog", "区"))
        self.labelUsrname_5.setText(_translate("Dialog", "地点"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. <span style=\" font-weight:600;\">不在校</span>时，需要填写上述四个输入框；<span style=\" font-weight:600;\">在校时</span>可以不用填。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. 填写时，<span style=\" font-weight:600;\">请加后缀</span>，比如江苏省，扬州市，邗江区；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. 直辖市第一个框不需要后缀，比如北京，北京市，东城区；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. 地点随便填</p></body></html>"))
import source_rc
